generer_le_crud_homepage:
    path:     /strange_bug
    defaults: { _controller: GenererLeCrudBundle:Default:index }

generer_le_crud_flight:
    resource: "@GenererLeCrudBundle/Resources/config/routing/flight.yml"
    prefix:   /flight

generer_le_crud_terrain:
    resource: "@GenererLeCrudBundle/Resources/config/routing/terrain.yml"
    prefix:   /terrain

generer_le_crud_reservation:
    resource: "@GenererLeCrudBundle/Resources/config/routing/reservation.yml"
    prefix:   /